# Generated by Django 2.1.4 on 2018-12-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('imgUrl', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iToken', models.CharField(max_length=500)),
                ('expiresAt', models.CharField(max_length=250)),
                ('token', models.CharField(max_length=500)),
                ('tpagaPaymentUrl', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=80)),
                ('customerEmail', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='purchasedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('itemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniapp.item')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp.order')),
            ],
        ),
    ]
