# Generated by Django 2.1.4 on 2018-12-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tpagaPaymentUrl',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
