# Generated by Django 2.1.4 on 2018-12-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='itemId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='miniapp.item'),
        ),
    ]
