# Generated by Django 2.1.4 on 2018-12-23 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0004_auto_20181222_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='itemId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', related_query_name='item', to='miniapp.item'),
        ),
    ]
