# Generated by Django 2.1.4 on 2018-12-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_auto_20181223_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='iToken',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
