# Generated by Django 2.1.4 on 2018-12-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0006_auto_20181225_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiresAt',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
